export const dummy_data = [
    {
        day: 'Legs & shoulders',
        title: 'DUMBBLE SQUAT',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'ARNOLD PRESS',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'DUMBBLE SET-UP',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'WIDE-GRIP UP RIGHT ROW',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'SISSY SQUAT',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'DUMBBELL LATERAL RAISE',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'ROMANIAN DEADLIFT',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'DUMBBELL BENT-OVER RAISE',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'SEATED CALF RAISE',
        set: 3,
        rep: '10',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Legs & shoulders',
        title: 'V-UP',
        set: 3,
        rep: '10',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'INCLINE BENCH PRESS',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'DUMBBELL BENTOVER ROW',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'DUMBBELL BENCH PRESS',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'STRAIGHT-ARM PULLBACK',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'DUMBBELL PULLOVER',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'DUMBBELL SHRUG',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'DECLINE DUMBBELL FLYE',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Cheest & Back',
        title: 'DOUBLE CRUNCH',
        set: 2,
        rep: '12',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'STANDING DUMBBELL BICEPS CURL',
        set: 3,
        rep: '8 - 10',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'DUMBBELL OVERHEAD TRICEPS EXTENSION',
        set: 3,
        rep: '8 - 10',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'WEIGHTED BENCH DIP',
        set: 2,
        rep: '8 - 10',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'ONE-ARM PREACHER CURL',
        set: 3,
        rep: '8 - 10',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'DUMBBELL LYING TRICEPS EXTENSION',
        set: 3,
        rep: '8 - 10',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'SEATED REVERSE DUMBBELL CURL',
        set: 2,
        rep: '8 - 10',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Arams & Sholders',
        title: 'WEIGHTED CRUNCH',
        set: 3,
        rep: '15',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'NEUTRAL-GRIP DUMBBELL INCLINE BENCH PRESS',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'DUMBBELL BENTOVER ROW',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'DUMBBELL PULLOVER',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'DUMBBELL SHRUG',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'WEIGHTED BENCH DIP',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'DUMBBELL LYING TRICEPS EXTENSION',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'DECLINE DUMBBELL FLYE',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Triceps & Abs',
        title: 'DOUBLE CRUNCH',
        set: 4,
        rep: '15',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'STANDING DUMBBELL BICEPS CURL',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'DUMBBELL OVERHEAD TRICEPS EXTENSION',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'ALTERNATING INCLINE DUMBBELL BICEPS CURL',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'WEIGHTED BENCH DIP',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'ONE-ARM PREACHER CURL',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'REVERSE CURL',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Lats & Biceps',
        title: 'WEIGHTED CRUNCH',
        set: 4,
        rep: '15',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'DUMBBLE SQUAT',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'ARNOLD PRESS',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'NEUTRAL-GRIP DUMBBELL INCLINE BENCH PRESS',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'DUMBBELL STRAIGHT-ARM PULLBACK',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'DUMBBELL OVERHEAD TRICEPS EXTENSION',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'ALTERNATING INCLINE DUMBBELL BICEPS CURL',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'STANDING DUMBBELL BICEPS CURL',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'DUMBBELL OVERHEAD TRICEPS EXTENSION',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'NEUTRAL-GRIP DUMBBELL INCLINE BENCH PRESS',
        set: 4,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
    {
        day: 'Whole Body',
        title: 'DUMBBELL BENTOVER ROW',
        set: 3,
        rep: '10 - 12',
        rest: '1min',
        value: true,
        bgColor: '',
    },
]