export const dummy_data = [
    {
        title: 'DUMBBLE SQUAT',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'ARNOLD PRESS',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'DUMBBLE SET-UP',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'WIDE-GRIP UP RIGHT ROW',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'SISSY SQUAT',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'DUMBBELL LATERAL RAISE',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'ROMANIAN DEADLIFT',
        set: 3,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'DUMBBELL BENT-OVER RAISE',
        set: 2,
        rep: '6 - 8',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'SEATED CALF RAISE',
        set: 3,
        rep: '10',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },
    {
        title: 'V-UP',
        set: 3,
        rep: '10',
        rest: '90sec - 2min',
        value: true,
        bgColor: '',
    },

]